name: Build

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - runs-on: ubuntu-22.04
            os: linux
            arch: x86_64
          - runs-on: macos-14
            os: macos
            arch: arm64
          - runs-on: macos-13
            os: macos
            arch: x86_64
    runs-on: ${{ matrix.config.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/checkout@v4
        with:
          repository: llvm/llvm-project
          path: llvm-project
      - name: Install dependencies
        run: ./scripts/install-${{ matrix.config.os }}.sh
      - name: Build clang-format
        run: ./scripts/build-${{ matrix.config.os }}.sh
      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: clang-format-${{ matrix.config.os }}-${{ matrix.config.arch }}
          path: llvm-project/build/bin/clang-format
